# Generated by Django 4.2 on 2023-04-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
    ]
