# Generated by Django 4.2 on 2023-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/profilepic.png', upload_to='profile_pictures'),
        ),
    ]
